# Generated by Django 4.2.6 on 2023-11-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(help_text='Enter your bio here...', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('postdate', models.DateField()),
                ('content', models.TextField(help_text='Enter your blog here...', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.author')),
            ],
            options={
                'ordering': ['postdate'],
            },
        ),
    ]
